-- Ejecutar una vez sobre la base existente. No modifica peliculas ni videojuegos.
-- Si ya existen estas tablas, comparar sus esquemas antes de ejecutar.
BEGIN;
CREATE TABLE videojuegos (
    id_videojuego       SERIAL PRIMARY KEY,
    titulo              VARCHAR(150) NOT NULL,
    genero              VARCHAR(100),
    plataforma          VARCHAR(100),
    anio_lanzamiento    INTEGER,
    calificacion        NUMERIC(3,1),
    desarrollador       VARCHAR(150),
    jugadores           VARCHAR(50),
    fecha_registro      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE peliculas (
    id_pelicula         SERIAL PRIMARY KEY,
    titulo              VARCHAR(150) NOT NULL,
    genero              VARCHAR(100),
    plataforma          VARCHAR(100),
    anio_lanzamiento    INTEGER,
    calificacion        NUMERIC(3,1),
    director            VARCHAR(150),
    actores             TEXT,
    productora          VARCHAR(150),
    duracion_minutos    INTEGER,
    clasificacion       VARCHAR(20),
    fecha_registro      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL CHECK (length(trim(nombre)) > 0),
    correo VARCHAR(254) NOT NULL UNIQUE CHECK (correo = lower(correo)),
    password TEXT NOT NULL,
    rol VARCHAR(10) NOT NULL DEFAULT 'usuario' CHECK (rol IN ('usuario','admin')),
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE conversaciones (
    id_conversacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE mensajes (
    id_mensaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conversacion INTEGER NOT NULL REFERENCES conversaciones(id_conversacion) ON DELETE CASCADE,
    rol VARCHAR(10) NOT NULL CHECK (rol IN ('user','assistant')),
    contenido TEXT NOT NULL,
    fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE consumo_tokens (
    id_consumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    categoria VARCHAR(12) NOT NULL CHECK (categoria IN ('peliculas','videojuegos')),
    tokens INTEGER NOT NULL CHECK (tokens >= 0),
    fecha TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Tabla adicional para que cerrar sesión invalide el token inmediatamente.
CREATE TABLE sesiones (
    token_hash VARCHAR(64) PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    fecha_expiracion TIMESTAMPTZ NOT NULL
);
CREATE INDEX ON conversaciones(id_usuario, fecha_creacion);
CREATE INDEX ON mensajes(id_conversacion, fecha);
CREATE INDEX ON consumo_tokens(id_usuario, categoria, fecha);
CREATE INDEX ON sesiones(id_usuario);
COMMIT;
